export const state = {
  models: [],
  knowledgeBases: [],
  currentSessionId: null,
  selectedKnowledgeBaseId: null,
  selectedChatModelConfigId: "",
  selectedReasoningEffort: "default",
  selectedEmbeddingModelConfigId: "",
  selectedChatKnowledgeBaseId: "",
  selectedDocumentKnowledgeBaseId: null,
  selectedRetrievalKnowledgeBaseId: null,
  chatAttachments: [],
  currentUser: null,
  oauthProviders: {},
  sending: false,
  activeChatController: null,
  activeRunReconnectController: null,
  activeRunId: null,
  activeRunMessageId: null,
  autoOpenedRunId: null,
  lastChatRequest: null,
  chatQueue: [],
  chatQueuePaused: false,
  chatQueueBlockReason: "",
  chatQueueSequence: 0,
};

export const messageRetryRequests = new Map();
